/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package teste1;

public class Library {
	
	public static void main(String[] args) {
		var name = "Jose";
		System.out.println(name.getClass());
	}
}
